import { Listing } from './supabase'

// Données fictives pour le développement (Phase 1)
export const mockListings: Listing[] = [
  {
    id: '1',
    user_id: 'user-1',
    titre: 'Toyota Corolla 2019 - Très bon état',
    description: 'Voiture en excellent état, service régulier, une seule propriétaire.',
    prix: 450000,
    categorie: 'vehicule',
    sous_categorie: 'Voiture',
    ville: 'Port-Louis',
    localisation_lat: -20.1609,
    localisation_lng: 57.4977,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: 'automatique',
    kilometrage: 45000,
    carburant: 'essence',
    annee: 2019,
    location_type: null,
    vehicule_type: null,
    type_bien: null,
    surface: null,
    etat: null,
    piece: null,
    type_electromenager: null,
    meuble: null,
    nb_chambres: null,
  },
  {
    id: '2',
    user_id: 'user-2',
    titre: 'Appartement F3 à louer - Quatre-Bornes',
    description: 'Bel appartement meublé, 3 chambres, parking inclus.',
    prix: 18000,
    categorie: 'immobilier',
    sous_categorie: 'Location',
    ville: 'Quatre-Bornes',
    localisation_lat: -20.2656,
    localisation_lng: 57.4796,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: null,
    kilometrage: null,
    carburant: null,
    annee: null,
    location_type: null,
    vehicule_type: null,
    type_bien: 'appartement',
    surface: 85,
    etat: null,
    piece: null,
    type_electromenager: null,
    meuble: true,
    nb_chambres: 3,
  },
  {
    id: '3',
    user_id: 'user-3',
    titre: 'Canapé 3 places - Comme neuf',
    description: 'Canapé en tissu gris, acheté il y a 6 mois, déménagement obligatoire.',
    prix: 8500,
    categorie: 'maison',
    sous_categorie: 'Ameublement',
    ville: 'Curepipe',
    localisation_lat: -20.3130,
    localisation_lng: 57.5257,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: null,
    kilometrage: null,
    carburant: null,
    annee: null,
    location_type: null,
    vehicule_type: null,
    type_bien: null,
    surface: null,
    etat: 'neuf',
    piece: 'salon',
    type_electromenager: null,
    meuble: null,
    nb_chambres: null,
  },
  {
    id: '4',
    user_id: 'user-1',
    titre: 'Honda PCX 150cc 2022',
    description: 'Scooter en parfait état, faible kilométrage, révision faite.',
    prix: 95000,
    categorie: 'vehicule',
    sous_categorie: 'Scooter',
    ville: 'Rose-Hill',
    localisation_lat: -20.2350,
    localisation_lng: 57.4637,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: 'automatique',
    kilometrage: 8000,
    carburant: null,
    annee: 2022,
    location_type: null,
    vehicule_type: null,
    type_bien: null,
    surface: null,
    etat: null,
    piece: null,
    type_electromenager: null,
    meuble: null,
    nb_chambres: null,
  },
  {
    id: '5',
    user_id: 'user-4',
    titre: 'Villa 4 chambres à vendre - Tamarin',
    description: 'Magnifique villa avec piscine, vue mer, terrain 500m².',
    prix: 8500000,
    categorie: 'immobilier',
    sous_categorie: 'Vente',
    ville: 'Tamarin',
    localisation_lat: -20.3233,
    localisation_lng: 57.3727,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: null,
    kilometrage: null,
    carburant: null,
    annee: null,
    location_type: null,
    vehicule_type: null,
    type_bien: 'maison',
    surface: 250,
    etat: null,
    piece: null,
    type_electromenager: null,
    meuble: null,
    nb_chambres: 4,
  },
  {
    id: '6',
    user_id: 'user-5',
    titre: 'Réfrigérateur Samsung 350L',
    description: 'Réfrigérateur en bon état, fonctionne parfaitement.',
    prix: 12000,
    categorie: 'maison',
    sous_categorie: 'Électroménager',
    ville: 'Vacoas',
    localisation_lat: -20.2989,
    localisation_lng: 57.4780,
    photos: [],
    actif: true,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    boite_vitesse: null,
    kilometrage: null,
    carburant: null,
    annee: null,
    location_type: null,
    vehicule_type: null,
    type_bien: null,
    surface: null,
    etat: 'bon état',
    piece: null,
    type_electromenager: 'cuisine',
    meuble: null,
    nb_chambres: null,
  },
]

// Formate le prix en Roupies Mauriciennes
export function formatPrix(prix: number): string {
  if (prix >= 1000000) {
    return `Rs ${(prix / 1000000).toFixed(1)}M`
  }
  if (prix >= 1000) {
    return `Rs ${(prix / 1000).toFixed(0)}K`
  }
  return `Rs ${prix.toLocaleString('fr-FR')}`
}

// Formate la date relative
export function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffH = Math.floor(diffMs / (1000 * 60 * 60))
  const diffD = Math.floor(diffH / 24)

  if (diffH < 1) return "À l'instant"
  if (diffH < 24) return `Il y a ${diffH}h`
  if (diffD < 7) return `Il y a ${diffD}j`
  return date.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short' })
}
